@startuml postsdb

entity Posts {
  +id : INTEGER <<PK>>
  +subject : TEXT <<NOT NULL>>
  +content : TEXT <<NOT NULL>>
  +author_id : TEXT <<NOT NULL>>
  +address : TEXT <<NOT NULL>>
  +tags : TEXT
  +created_at : DATETIME <<DEFAULT CURRENT_TIMESTAMP>>
  +updated_at : DATETIME <<DEFAULT CURRENT_TIMESTAMP>>
}

@enduml